//! ICC colour management built on Little CMS 2 (`lcms2`).
//!
//! Two jobs:
//!
//! * **Profile bytes** — [`srgb_icc_bytes`] and [`cmyk_icc_bytes`] serialise
//!   ICC profiles that [`crate::io::pdf_print`] embeds into exported PDFs as
//!   the `/OutputIntent` `/DestOutputProfile`. No profile file is shipped or
//!   downloaded: everything is generated by lcms2 at runtime, so builds stay
//!   network-free.
//! * **Colour conversion** — [`rgb_to_cmyk_icc`] runs a real ICC transform
//!   (sRGB profile → PCS Lab → CMYK press profile). [`rgb_to_cmyk`] wraps it
//!   and falls back to the naive UCR model of [`crate::core::print`] whenever
//!   the C engine cannot be initialised.
//!
//! ## The synthetic CMYK press profile
//!
//! Little CMS ships no process-CMYK profile and fetching one over the network
//! is not allowed here, so [`cmyk_icc_bytes`] *builds* one with lcms2's own
//! C API: an ICC v4 output profile (CMYK ↔ Lab PCS) whose `BToA0` tag is a
//! CLUT filled from Amata's UCR separation model — the same maths as
//! [`crate::core::print::rgb_to_cmyk_ink`].
//!
//! The profile carries both directions: `BToA0` (Lab PCS → CMYK, 17³ nodes)
//! for rendering and for the `/OutputIntent`, and a coarser `AToB0`
//! (CMYK → Lab, 9⁴ nodes) so the profile round-trips and can be used for
//! proofing/black-point look-ups. Both CLUTs are the same UCR model seen from
//! the two sides, so they stay self-consistent.
//!
//! What lcms2 does here is the real ICC work: PCS handling, D50 adaptation,
//! tone curves, intents, LUT serialisation and, at conversion time,
//! interpolation of the profile LUTs. What is *ours* (and therefore not a
//! measured press profile) is the gamut model inside those LUTs: it is a
//! deterministic UCR/GCR model, not Japan Color 2001 Coated or any other
//! measured characterisation. See `CLUT_PRESS_MODEL` below.

use lcms2::{Error, Intent, LCMSResult, PixelFormat, Profile, Transform};
use lcms2_sys as ffi;
use std::cell::RefCell;
use std::os::raw::c_void;
use std::ptr;
use std::sync::OnceLock;

/// CLUT resolution of the synthetic CMYK profile's `BToA0` LUT
/// (33³ nodes × 4 outputs ≈ 287 KiB of table — the resolution real press
/// profiles ship, and what keeps grid interpolation off the exported inks).
const GRID: usize = 33;

/// Coarser grid for the reverse (`A2B0`) LUT: 9⁴ nodes × 3 outputs ≈ 38 KiB.
/// It is only read for proofing/black-point style look-ups, never for
/// exported colour.
const A2B_GRID: usize = 9;

/// Documentation pointer for the press model baked into the CMYK LUTs.
const CLUT_PRESS_MODEL: &str =
    "Amata UCR (naive under-colour removal), not a measured press characterisation";

/// D50 tristimulus: the ICC PCS white point.
const D50: [f64; 3] = [0.9642, 1.0, 0.8249];

/// sRGB primaries adapted to D50 — the matrix printed in sRGB ICC profiles.
const SRGB_D50_TO_XYZ: [[f64; 3]; 3] = [
    [0.4360747, 0.3850649, 0.1430804],
    [0.2225045, 0.7168786, 0.0606169],
    [0.0139322, 0.0971045, 0.7141733],
];

/// Inverse of [`SRGB_D50_TO_XYZ`]: XYZ (D50) → linear sRGB.
const XYZ_TO_SRGB_D50: [[f64; 3]; 3] = [
    [3.1338561, -1.6168667, -0.4906146],
    [-0.9787684, 1.9161415, 0.0334540],
    [0.0719453, -0.2289914, 1.4052427],
];

// ---------------------------------------------------------------------------
// Colour maths used to fill the profile LUTs
// ---------------------------------------------------------------------------

fn mat3(m: &[[f64; 3]; 3], v: [f64; 3]) -> [f64; 3] {
    [
        m[0][0] * v[0] + m[0][1] * v[1] + m[0][2] * v[2],
        m[1][0] * v[0] + m[1][1] * v[1] + m[1][2] * v[2],
        m[2][0] * v[0] + m[2][1] * v[1] + m[2][2] * v[2],
    ]
}

/// CIE Lab → XYZ under the D50 PCS illuminant.
fn lab_to_xyz(l: f64, a: f64, b: f64) -> [f64; 3] {
    let fy = (l + 16.0) / 116.0;
    let fx = fy + a / 500.0;
    let fz = fy - b / 200.0;
    let cube = |t: f64| {
        if t > 6.0 / 29.0 {
            t * t * t
        } else {
            3.0 * (6.0 / 29.0) * (6.0 / 29.0) * (t - 4.0 / 29.0)
        }
    };
    [D50[0] * cube(fx), D50[1] * cube(fy), D50[2] * cube(fz)]
}

/// XYZ (D50) → CIE Lab.
fn xyz_to_lab(x: f64, y: f64, z: f64) -> (f64, f64, f64) {
    let root = |t: f64| {
        if t > (6.0_f64 / 29.0_f64).powi(3) {
            t.cbrt()
        } else {
            t / (3.0 * (6.0 / 29.0) * (6.0 / 29.0)) + 4.0 / 29.0
        }
    };
    let fx = root(x / D50[0]);
    let fy = root(y / D50[1]);
    let fz = root(z / D50[2]);
    (116.0 * fy - 16.0, 500.0 * (fx - fy), 200.0 * (fy - fz))
}

fn srgb_encode(v: f64) -> f64 {
    if v <= 0.003_130_8 {
        12.92 * v
    } else {
        1.055 * v.powf(1.0 / 2.4) - 0.055
    }
}

fn srgb_decode(v: f64) -> f64 {
    if v <= 0.040_45 {
        v / 12.92
    } else {
        ((v + 0.055) / 1.055).powf(2.4)
    }
}

/// Naive under-colour removal, mirroring
/// [`crate::core::print::rgb_to_cmyk_ink`] in `f64` (the LUT stores `u16`).
fn ucr(r: f64, g: f64, b: f64) -> [f64; 4] {
    let k = 1.0 - r.max(g).max(b);
    if k >= 1.0 {
        return [0.0, 0.0, 0.0, 1.0];
    }
    let inv = 1.0 - k;
    [
        ((inv - r) / inv).clamp(0.0, 1.0),
        ((inv - g) / inv).clamp(0.0, 1.0),
        ((inv - b) / inv).clamp(0.0, 1.0),
        k,
    ]
}

/// PCS Lab → CMYK for the `B2A0` LUT (this is the press model, see module docs).
fn lab_to_cmyk(l: f64, a: f64, b: f64) -> [f64; 4] {
    // Zero luminance with non-zero chroma is not a colour any press can lay
    // down. XYZ→sRGB there returns denormal channel values, and the UCR
    // division by (1 − max) would amplify them into phantom CMY exactly at
    // the point where the model promises paper-free black — which is what
    // every neutral in the document samples against.
    if l <= 0.0 {
        return [0.0, 0.0, 0.0, 1.0];
    }
    let [x, y, z] = lab_to_xyz(l, a, b);
    let lin = mat3(&XYZ_TO_SRGB_D50, [x, y, z]);
    let enc = [
        srgb_encode(lin[0].clamp(0.0, 1.0)),
        srgb_encode(lin[1].clamp(0.0, 1.0)),
        srgb_encode(lin[2].clamp(0.0, 1.0)),
    ];
    ucr(enc[0], enc[1], enc[2])
}

/// Grid node index → normalised channel value (0…1) for a `grid`-node axis.
fn node_norm(i: usize, grid: usize) -> f64 {
    i as f64 / (grid - 1) as f64
}

/// Encode Lab into the ICC v4 16-bit PCS representation that lcms2 uses
/// internally (`L·65535/100`, `(a+128)·65535/255`, same for `b`).
fn encode_lab_v4(lab: [f64; 3]) -> [u16; 3] {
    // `lcms2`'s `cmsLabEncoded2Float` is the inverse of this exact mapping.
    let enc = |v: f64| (v * 257.0 + 0.5).clamp(0.0, 65535.0) as u16;
    [enc(lab[0] * 2.55), enc(lab[1] + 128.0), enc(lab[2] + 128.0)]
}

/// `B2A0` table (PCS Lab → device CMYK): `GRID³ × 4` u16.
fn build_b2a_table() -> Vec<u16> {
    let mut table = vec![0u16; GRID * GRID * GRID * 4];
    for li in 0..GRID {
        let l = node_norm(li, GRID) * 100.0;
        for ai in 0..GRID {
            let a = node_norm(ai, GRID) * 255.0 - 128.0;
            for bi in 0..GRID {
                let b = node_norm(bi, GRID) * 255.0 - 128.0;
                let cmyk = lab_to_cmyk(l, a, b);
                let base = ((li * GRID + ai) * GRID + bi) * 4;
                for (slot, value) in table[base..base + 4].iter_mut().zip(cmyk) {
                    *slot = (value * 65535.0).round().clamp(0.0, 65535.0) as u16;
                }
            }
        }
    }
    table
}

/// Exact inverse of [`ucr`]: CMYK → the sRGB triple that [`ucr`] maps to it
/// (for `k < 1`; the `k = 1` corner collapses to black either way).
fn ucr_inverse(c: f64, m: f64, y: f64, k: f64) -> [f64; 3] {
    let inv = 1.0 - k;
    [(1.0 - c) * inv, (1.0 - m) * inv, (1.0 - y) * inv]
}

/// sRGB (gamma-encoded, 0…1) → PCS Lab under D50.
fn srgb_to_lab(rgb: [f64; 3]) -> [f64; 3] {
    let lin = [
        srgb_decode(rgb[0]),
        srgb_decode(rgb[1]),
        srgb_decode(rgb[2]),
    ];
    let [x, y, z] = mat3(&SRGB_D50_TO_XYZ, lin);
    let (l, a, b) = xyz_to_lab(x, y, z);
    [l, a, b]
}

/// `AToB0` table (device CMYK → PCS Lab): `A2B_GRID⁴ × 3` u16.
///
/// The device side is the exact inverse of the model baked into
/// [`build_b2a_table`], so both LUTs describe one self-consistent press.
fn build_a2b_table() -> Vec<u16> {
    let mut table = vec![0u16; A2B_GRID * A2B_GRID * A2B_GRID * A2B_GRID * 3];
    for ci in 0..A2B_GRID {
        let c = node_norm(ci, A2B_GRID);
        for mi in 0..A2B_GRID {
            let m = node_norm(mi, A2B_GRID);
            for yi in 0..A2B_GRID {
                let y = node_norm(yi, A2B_GRID);
                for ki in 0..A2B_GRID {
                    let k = node_norm(ki, A2B_GRID);
                    let rgb = ucr_inverse(c, m, y, k);
                    let lab = encode_lab_v4(srgb_to_lab(rgb));
                    let base = (((ci * A2B_GRID + mi) * A2B_GRID + yi) * A2B_GRID + ki) * 3;
                    table[base..base + 3].copy_from_slice(&lab);
                }
            }
        }
    }
    table
}

// ---------------------------------------------------------------------------
// Profile construction (lcms2 C API)
// ---------------------------------------------------------------------------

/// Identity tone-curve stage (`channels` → `channels`).
///
/// # Safety
/// Uses raw lcms2 handles; every returned pointer is either handed to
/// `cmsPipelineInsertStage` or released by the caller.
unsafe fn identity_curves(channels: u32) -> *mut ffi::Stage {
    unsafe {
        let gamma = ffi::cmsBuildGamma(ptr::null_mut(), 1.0);
        if gamma.is_null() {
            return ptr::null_mut();
        }
        // The stage dups every curve, so the source is freed right away.
        let shared = vec![gamma; channels as usize];
        let stage = ffi::cmsStageAllocToneCurves(
            ptr::null_mut(),
            channels,
            shared.as_ptr() as *const *const ffi::ToneCurve,
        );
        ffi::cmsFreeToneCurve(gamma);
        stage
    }
}

/// Build a `[CurveSet, CLUT, CurveSet]` pipeline — the exact shape
/// `lutBToAType`/`lutAtoBType` writers accept. `grid` is the CLUT resolution
/// along each of the `in_ch` input axes.
///
/// # Safety
/// See [`identity_curves`]; on `None` nothing is leaked.
unsafe fn build_lut(
    grid: usize,
    in_ch: u32,
    out_ch: u32,
    table: &[u16],
) -> Option<*mut ffi::Pipeline> {
    unsafe {
        let pipeline = ffi::cmsPipelineAlloc(ptr::null_mut(), in_ch, out_ch);
        if pipeline.is_null() {
            return None;
        }
        let stages = [
            (identity_curves(in_ch), ffi::StageLoc::AT_BEGIN),
            (
                ffi::cmsStageAllocCLut16bit(
                    ptr::null_mut(),
                    grid as u32,
                    in_ch,
                    out_ch,
                    table.as_ptr(),
                ),
                ffi::StageLoc::AT_END,
            ),
            (identity_curves(out_ch), ffi::StageLoc::AT_END),
        ];
        if stages.iter().any(|(stage, _)| stage.is_null()) {
            for (stage, _) in stages {
                if !stage.is_null() {
                    ffi::cmsStageFree(stage);
                }
            }
            ffi::cmsPipelineFree(pipeline);
            return None;
        }
        for (i, (stage, loc)) in stages.iter().enumerate() {
            if ffi::cmsPipelineInsertStage(pipeline, *loc, *stage) == 0 {
                // A failed insert still linked `stage`; the rest stay ours.
                for (left, _) in &stages[i + 1..] {
                    ffi::cmsStageFree(*left);
                }
                ffi::cmsPipelineFree(pipeline);
                return None;
            }
        }
        Some(pipeline)
    }
}

/// Serialise a LUT into the profile under `sig`.
///
/// # Safety
/// `profile` must be an open lcms2 profile handle.
unsafe fn write_lut(
    profile: ffi::HPROFILE,
    sig: ffi::TagSignature,
    grid: usize,
    in_ch: u32,
    out_ch: u32,
    table: &[u16],
) -> bool {
    unsafe {
        let Some(pipeline) = build_lut(grid, in_ch, out_ch, table) else {
            return false;
        };
        // cmsWriteTag duplicates the pipeline, so ours is freed afterwards.
        let written = ffi::cmsWriteTag(
            profile,
            sig,
            pipeline as *const ffi::Pipeline as *const c_void,
        ) != 0;
        ffi::cmsPipelineFree(pipeline);
        written
    }
}

/// Description / copyright tags.
///
/// # Safety
/// `profile` must be an open lcms2 profile handle.
unsafe fn write_text_tags(profile: ffi::HPROFILE) -> bool {
    unsafe {
        // `CLUT_PRESS_MODEL` goes into the human-readable description so the
        // exported profile states its own provenance.
        let name = format!("Amata press CMYK - {}\0", CLUT_PRESS_MODEL);
        let copyright = b"No copyright, generated by Amata\0";
        let lang = b"en\0";
        let country = b"US\0";
        let desc = ffi::cmsMLUalloc(ptr::null_mut(), 1);
        if desc.is_null() {
            return false;
        }
        let ok = ffi::cmsMLUsetASCII(
            desc,
            lang.as_ptr().cast(),
            country.as_ptr().cast(),
            name.as_ptr().cast(),
        ) != 0
            && ffi::cmsWriteTag(
                profile,
                ffi::TagSignature::ProfileDescriptionTag,
                desc as *const c_void,
            ) != 0;
        ffi::cmsMLUfree(desc);

        let cr = ffi::cmsMLUalloc(ptr::null_mut(), 1);
        if cr.is_null() {
            return ok;
        }
        let cr_ok = ffi::cmsMLUsetASCII(
            cr,
            lang.as_ptr().cast(),
            country.as_ptr().cast(),
            copyright.as_ptr().cast(),
        ) != 0
            && ffi::cmsWriteTag(
                profile,
                ffi::TagSignature::CopyrightTag,
                cr as *const c_void,
            ) != 0;
        ffi::cmsMLUfree(cr);
        ok && cr_ok
    }
}

/// D50 media white point tag (required for any sane PCS handling).
///
/// # Safety
/// `profile` must be an open lcms2 profile handle.
unsafe fn write_white_point(profile: ffi::HPROFILE) -> bool {
    unsafe {
        let d50: *const ffi::CIEXYZ = ffi::cmsD50_XYZ();
        ffi::cmsWriteTag(
            profile,
            ffi::TagSignature::MediaWhitePointTag,
            d50 as *const c_void,
        ) != 0
    }
}

/// Serialise an open profile to memory.
///
/// # Safety
/// `profile` must be an open lcms2 profile handle.
unsafe fn save_profile(profile: ffi::HPROFILE) -> Option<Vec<u8>> {
    unsafe {
        let mut len: u32 = 0;
        if ffi::cmsSaveProfileToMem(profile, ptr::null_mut(), &mut len) == 0 || len == 0 {
            return None;
        }
        let mut buf = vec![0u8; len as usize];
        if ffi::cmsSaveProfileToMem(profile, buf.as_mut_ptr().cast::<c_void>(), &mut len) == 0 {
            return None;
        }
        buf.truncate(len as usize);
        Some(buf)
    }
}

/// Build the synthetic CMYK output profile from scratch and serialise it.
///
/// Returns `None` when lcms2 refuses any step; callers then fall back to the
/// naive model (see [`rgb_to_cmyk`]).
fn build_cmyk_profile_bytes() -> Option<Vec<u8>> {
    // SAFETY: every handle comes from lcms2, is checked for null, and the
    // profile plus every pipeline/MLU we allocate is released before return.
    unsafe {
        let profile = ffi::cmsCreateProfilePlaceholder(ptr::null_mut());
        if profile.is_null() {
            return None;
        }
        ffi::cmsSetProfileVersion(profile, 4.3);
        ffi::cmsSetDeviceClass(profile, ffi::ProfileClassSignature::OutputClass);
        ffi::cmsSetColorSpace(profile, ffi::ColorSpaceSignature::CmykData);
        ffi::cmsSetPCS(profile, ffi::ColorSpaceSignature::LabData);
        ffi::cmsSetHeaderRenderingIntent(profile, ffi::Intent::RelativeColorimetric);

        let b2a = write_text_tags(profile)
            && write_white_point(profile)
            && write_lut(
                profile,
                ffi::TagSignature::BToA0Tag,
                GRID,
                3,
                4,
                &build_b2a_table(),
            );
        // The reverse LUT (proofing, black-point reads) is a bonus: if lcms2
        // declines it the profile still works as an output profile.
        let _ = write_lut(
            profile,
            ffi::TagSignature::AToB0Tag,
            A2B_GRID,
            4,
            3,
            &build_a2b_table(),
        );

        let bytes = if b2a { save_profile(profile) } else { None };
        ffi::cmsCloseProfile(profile);
        bytes
    }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// sRGB ICC profile (v4) bytes generated by lcms2 — used as the
/// `/DestOutputProfile` of RGB documents' `/OutputIntent`.
pub fn srgb_icc_bytes() -> Option<Vec<u8>> {
    Profile::new_srgb().icc().ok()
}

/// Cached bytes of the synthetic CMYK press profile.
///
/// The `CLUT_PRESS_MODEL` caveat applies: it is a deterministic UCR model,
/// not a measured press characterisation.
pub fn cmyk_icc_bytes() -> Option<Vec<u8>> {
    static CACHE: OnceLock<Option<Vec<u8>>> = OnceLock::new();
    CACHE.get_or_init(build_cmyk_profile_bytes).clone()
}

/// ICC profile bytes matching what the PDF will be tagged with: CMYK when the
/// document prints plates, sRGB otherwise.
pub fn output_intent_icc_bytes(cmyk: bool) -> Option<Vec<u8>> {
    if cmyk {
        cmyk_icc_bytes()
    } else {
        srgb_icc_bytes()
    }
}

/// ICC-transformed RGB → CMYK. `rgb[3]` (alpha) is ignored, exactly like
/// [`crate::core::print::rgb_to_cmyk_ink`]; the result is CMYK in `0…1`.
///
/// `None` means the engine could not be built or the transform failed —
/// callers should then use [`rgb_to_cmyk_fallback`].
pub fn rgb_to_cmyk_icc(rgb: [f32; 4]) -> Option<[f32; 4]> {
    let src = [
        (rgb[0].clamp(0.0, 1.0) * 255.0).round() as u8,
        (rgb[1].clamp(0.0, 1.0) * 255.0).round() as u8,
        (rgb[2].clamp(0.0, 1.0) * 255.0).round() as u8,
    ];
    with_transform(|t| {
        let mut out = [0u8; 4];
        t.transform_pixels(&src, &mut out);
        [
            out[0] as f32 / 255.0,
            out[1] as f32 / 255.0,
            out[2] as f32 / 255.0,
            out[3] as f32 / 255.0,
        ]
    })
}

/// RGB → CMYK with a guaranteed answer: the ICC engine when it is available,
/// the legacy naive-UCR model otherwise.
pub fn rgb_to_cmyk(rgb: [f32; 4]) -> [f32; 4] {
    rgb_to_cmyk_icc(rgb).unwrap_or_else(|| rgb_to_cmyk_fallback(rgb))
}

/// Legacy path: [`crate::core::print::rgb_to_cmyk_ink`].
pub fn rgb_to_cmyk_fallback(rgb: [f32; 4]) -> [f32; 4] {
    crate::core::print::rgb_to_cmyk_ink(rgb[0], rgb[1], rgb[2])
}

// ---------------------------------------------------------------------------
// Transform cache
// ---------------------------------------------------------------------------

thread_local! {
    /// One sRGB → CMYK transform per thread (LCMS transforms are not `Sync`).
    static RGB_TO_CMYK: RefCell<Option<Transform<u8, u8>>> = const { RefCell::new(None) };
}

/// Run `f` with the thread's transform, building it on first use.
fn with_transform<T>(f: impl FnOnce(&Transform<u8, u8>) -> T) -> Option<T> {
    RGB_TO_CMYK.with(|cell| {
        let mut slot = cell.borrow_mut();
        if slot.is_none() {
            *slot = build_transform().ok();
        }
        slot.as_ref().map(f)
    })
}

/// sRGB → synthetic CMYK, relative colorimetric (no BPC so that paper white
/// stays `0` and ink black stays `K = 1`).
fn build_transform() -> LCMSResult<Transform<u8, u8>> {
    let bytes = cmyk_icc_bytes().ok_or(Error::ObjectCreationError)?;
    let cmyk = Profile::new_icc(&bytes)?;
    let srgb = Profile::new_srgb();
    Transform::new(
        &srgb,
        PixelFormat::RGB_8,
        &cmyk,
        PixelFormat::CMYK_8,
        Intent::RelativeColorimetric,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn colour_maths_round_trip() {
        // sRGB white is exactly the D50 white point.
        let [x, y, z] = mat3(&SRGB_D50_TO_XYZ, [1.0, 1.0, 1.0]);
        assert!((x - D50[0]).abs() < 1e-3);
        assert!((y - D50[1]).abs() < 1e-3);
        assert!((z - D50[2]).abs() < 1e-3);
        let (l, a, b) = xyz_to_lab(x, y, z);
        assert!((l - 100.0).abs() < 5.0 && a.abs() < 10.0 && b.abs() < 10.0);
        // Lab → XYZ → Lab is stable away from the origin.
        let [x2, y2, z2] = lab_to_xyz(50.0, 20.0, -30.0);
        let (l2, a2, b2) = xyz_to_lab(x2, y2, z2);
        assert!((l2 - 50.0).abs() < 5.0);
        assert!((a2 - 20.0).abs() < 10.0);
        assert!((b2 + 30.0).abs() < 10.0);
    }

    #[test]
    fn rgb_to_cmyk_stays_on_the_legacy_model() {
        // The ICC path must be a drop-in for the UCR model it embeds in the
        // profile: 8-bit LUT quantisation is allowed to nudge the answer,
        // a different separation is not.
        let cases = [
            [1.0, 1.0, 1.0, 1.0],
            [0.0, 0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0, 1.0],
            [0.5, 0.5, 0.5, 1.0],
            [0.2, 0.4, 0.8, 1.0],
        ];
        for rgb in cases {
            let icc = rgb_to_cmyk(rgb);
            let legacy = rgb_to_cmyk_fallback(rgb);
            for i in 0..4 {
                assert!(
                    (icc[i] - legacy[i]).abs() < 0.06,
                    "rgb_to_cmyk({rgb:?})[{i}] = {} vs legacy {}",
                    icc[i],
                    legacy[i]
                );
            }
        }
        // Alpha is never part of the conversion, in either path.
        assert!(rgb_to_cmyk([1.0, 1.0, 1.0, 0.25])[3] < 0.01);
    }

    #[test]
    fn ucr_matches_legacy_model() {
        let cases = [
            [1.0, 1.0, 1.0, 1.0],
            [0.0, 0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0, 1.0],
            [0.5, 0.5, 0.5, 1.0],
            [0.2, 0.4, 0.8, 1.0],
        ];
        for rgb in cases {
            let mine = ucr(rgb[0] as f64, rgb[1] as f64, rgb[2] as f64);
            let legacy = crate::core::print::rgb_to_cmyk_ink(rgb[0], rgb[1], rgb[2]);
            for i in 0..4 {
                assert!(
                    (mine[i] - legacy[i] as f64).abs() < 1e-6,
                    "ucr({rgb:?})[{i}] = {} vs legacy {}",
                    mine[i],
                    legacy[i]
                );
            }
        }
    }
}
